name: cargo-bump
description: Run the cargo-bump command
inputs:
  working-directory:
    description: Cargo.toml directory
  root-directory:
    description: Cargo.lock directory
  release-type:
    description: Release type - `major`, `minor`, `patch`
    required: true
  sync-cmd:
    description: Cargo command used to sync the version change with Cargo.lock
    default: check --workspace
  cargo-semver-version:
    description: cargo-semver version
    default: ^1.0.0-alpha.3
branding:
  icon: activity
  color: orange
runs:
  using: composite
  steps:
    - name: Install
      uses: alorel-actions/cargo-global-dep@v1
      with:
        name: cargo-semver
        version: ${{ inputs.cargo-semver-version }}
    - name: Bump
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: cargo semver bump ${{ inputs.release-type }} && git add Cargo.toml
    - name: Sync
      shell: bash
      working-directory: ${{ inputs.root-directory }}
      run: cargo ${{ inputs.sync-cmd }} && git add Cargo.lock
      env:
        RUSTFLAGS: --allow warnings
