name: cargo-bump
description: Run the cargo-bump command
inputs:
  working-directory:
    description: Cargo.toml directory
  root-directory:
    description: Cargo.lock directory
  release-type:
    description: Release type - `major`, `minor`, `patch`
    required: true
  sync-cmd:
    description: Cargo command used to sync the version change with Cargo.lock
    default: check --workspace
  cargo-bump-version:
    description: cargo-bump version
    default: ^1
branding:
  icon: activity
  color: orange
runs:
  using: composite
  steps:
    - name: Echo args
      shell: bash
      if: ${{ inputs.cargo-bump-version }}
      id: args
      run: echo "args=--version ${{ inputs.cargo-bump-version }}" >> $GITHUB_OUTPUT
    - name: Install
      shell: bash
      run: cargo install cargo-bump --debug ${{ steps.args.outputs.args }}
      continue-on-error: true
      id: install
    - name: Check if it's installed
      if: ${{ steps.install.outcome == 'failure' }}
      shell: bash
      run: which cargo-bump
    - name: Bump
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: cargo-bump ${{ inputs.release-type }} && git add Cargo.toml
    - name: Sync
      shell: bash
      working-directory: ${{ inputs.root-directory }}
      run: cargo ${{ inputs.sync-cmd }} && git add Cargo.lock
      env:
        RUSTFLAGS: --allow warnings
