# https://github.com/Ezard/semantic-prs

enabled: true
commitsOnly: true
types:
  - feat
  - fix
  - docs
  - refactor
  - build
  - ci
  - chore
  - deps
  - deps-dev
scopes:
  - dev
  - init
  - rdme
  - bump
