name: cargo-rdme
description: Run the cargo-rdme --check command
inputs:
  working-directory:
    description: Run in the specified directory
  version:
    description: Version to install.
    default: ^1
  no-fail-on-warnings:
    description: Pass the `no-fail-on-warnings` flag
  intralinks-strip-links:
    description: Pass the `intralinks-strip-links` flag
branding:
  icon: activity
  color: orange
runs:
  using: composite
  steps:
    - name: Install
      uses: alorel-actions/cargo-global-dep@v1
      with:
        name: cargo-rdme
        version: ${{ inputs.version }}

    - shell: bash
      if: ${{ inputs.no-fail-on-warnings == 'true' || inputs.no-fail-on-warnings == 'TRUE' }}
      id: nfow
      run: echo "args=--no-fail-on-warnings" >> $GITHUB_OUTPUT

    - shell: bash
      if: ${{ inputs.intralinks-strip-links == 'true' || inputs.intralinks-strip-links == 'TRUE' }}
      id: intra
      run: echo "args=--intralinks-strip-links" >> $GITHUB_OUTPUT
  
    - name: Run check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: cargo rdme --check ${{ steps.nfow.outputs.args }} ${{ steps.intra.outputs.args }}
