name: Install cargo dependency
description: Install a cargo dependency
inputs:
  name:
    description: Run in the specified directory
  version:
    description: Version to install
  flags:
    description: Other flags to pass to cargo install
runs:
  using: composite
  steps:
    - name: Echo args
      shell: bash
      if: ${{ inputs.version }}
      id: args
      run: echo "args=--version ${{ inputs.version }}" >> $GITHUB_OUTPUT
    - name: Install
      shell: bash
      run: cargo install ${{ inputs.name }} ${{ steps.args.outputs.args }} ${{ inputs.flags }}
      continue-on-error: true
      id: install
    - name: Check if it's installed
      if: ${{ steps.install.outcome == 'failure' }}
      shell: bash
      run: which ${{ inputs.name }}
