name: Test
on:
  workflow_call:
    inputs:
      cargo-rdme-no-fail-on-warnings:
        description: Add the no-fail-on-warnings flag to cargo-rdme
        type: boolean

      cargo-rdme-intralinks-strip-links:
        description: Add the intralinks-strip-links flag to cargo-rdme
        type: boolean
      
      nightly-toolchain:
        description: Nightly toolchain to use
        default: nightly
        type: string
      
      min-toolchain:
        description: Minimum toolchain to test
        required: true
        type: string

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: --deny warnings

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v1
        id: toolchain
        with:
          components: rustfmt,clippy
          cache-prefix: lint
          local: true

      - name: Fmt
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --workspace --tests

      - name: Doc
        run: cargo doc --workspace --no-deps && rm -rf target/doc

      - name: cargo-rdme
        uses: alorel-actions/cargo/rdme@v1
        with:
          no-fail-on-warnings: ${{ inputs.cargo-rdme-no-fail-on-warnings }}
          intralinks-strip-links: ${{ inputs.cargo-rdme-intralinks-strip-links }}

  nightly-test:
    name: Rust nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v1
        with:
          toolchain: ${{ inputs.nightly-toolchain }}
          cache-prefix: test
          local: true
          components: llvm-tools-preview

      - name: Examples & unit tests
        uses: alorel-actions/cargo/llvm-cov@v1
        with:
          output: unit.lcov
          args: --lcov --examples --tests --workspace

      - name: Doc tests
        uses: alorel-actions/cargo/llvm-cov@v1
        with:
          output: doc.lcov
          args: --lcov --doctests --workspace

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          files: unit.lcov doc.lcov
  
  test:
    name: Rust ${{matrix.toolchain}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - ${{ inputs.min-toolchain }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v1
        id: toolchain
        with:
          toolchain: ${{matrix.toolchain}}
          cache-prefix: test
          local: true

      - name: Build
        run: cargo build --workspace --tests --locked

      - name: Test
        run: cargo test --workspace --locked
